version: "3"
services:
  #test:
    #build: .
    #container_name: part3
    #ports:
    #  - 80:80
  coursematerial:
    image: vmtornikoski/part3_test:latest
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
