
name: Deploy to Heroku

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build, push and Deploy to Heroku
      uses: behe/heroku-build@v1 #akhileshns/heroku-deploy@v3.12.12
      with:
        api-key: ${{ secrets.HEROKU_API_KEY }}
        app-name: "ex31-vmtorn"
